### ISSUE TITLE
Improve AmbassadorList responsiveness

### ISSUE THREAD

**Issue by pjeweb** [abdullahmorrison/AlveusTwitchExtension#24]
Could we make the list a bit taller in smaller viewports? According to the twitch dev docs [1] the overlay can be up to 5rem from top/bottom. Another idea would be to move the scroll arrow button in front of the list to gain a few more pixels. I can make a pull request if you would consider it.

Current:
![Overlay at 1024 pixel width](https://user-images.githubusercontent.com/684458/213876989-5a0d72d5-cd02-4d4c-9ceb-69c528f019f4.png)

Proposed arrow button above list:
![Mockup arrow button above list](https://user-images.githubusercontent.com/684458/213877132-0e1602b5-7ba3-4ef3-8e80-977deb37c92a.png)

------------------

1) https://dev.twitch.tv/docs/extensions/designing/#video-overlay-extensions

**Comment by abdullahmorrison** [comment]
Yep, that would be great.

**Comment by abdullahmorrison** [comment]
In certain dimensions, the ambassador list is too large and the arrows get covered by the twitch volume mixer at the bottom of the twitch video. That needs to be fixed too.
