### ISSUE TITLE
Handle channels separately

### ISSUE THREAD

**Issue by abdullahmorrison** [abdullahmorrison/AlveusTwitchExtension#34]
### Discussed in https://github.com/abdullahmorrison/AlveusTwitchExtension/discussions/33

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **pjeweb** January 23, 2023</sup>
> I would propose to change the extension such that it only reacts to events (commands/title changes) for the channel it is displayed on. E.g. do not open a card on Mayas stream if a command is sent in the Alveus chat.
> 
> I am not sure where you would get that info. Maybe this would need to be set in the extension configuration by the streamer?</div>
> 

This would require the extension to know what channel it is installed in. If that can be done, the useChatCommand hook can also return what channel the chat command is called in.

**Comment by MattIPv4** [comment]
It sounds like the auth callback in the extension API should give you the current channel id: https://discuss.dev.twitch.tv/t/get-channel-id-where-the-extension-is-currently-displayed/16583
