### ISSUE TITLE
Existing testing code

### ISSUE THREAD

**Issue by MattIPv4** [abdullahmorrison/AlveusTwitchExtension#45]
:wave: Is the existing code for running tests within the repo wanted? `npm test` seems to invoke some templated tests that currently fail? Is it worth keeping these around (and maybe stubbing out what's currently failing), or would it be fine to just remove the tests and the testing dependencies?

**Comment by abdullahmorrison** [comment]
Those were just the template tests that came with create-react-app. I may eventually add tests but I haven't made a decision about what I want to do with them yet. I think it's best to leave it as is for now.

**Comment by MattIPv4** [comment]
Ack, works for me. Will leave them as is.

**Comment by pjeweb** [comment]
In case you want to add the basic render tests I added a test for the overlay app and fixed the panel one in #47
