### ISSUE TITLE
The same chat command cannot execute more than once in a row

### ISSUE THREAD

**Issue by abdullahmorrison** [abdullahmorrison/AlveusTwitchExtension#50]
because the overlay popup commands are controlled in its useEffect and the commands are a dependency within the useEffect, if the same command is called in chat, the useEffect will not execute that command because the useEffect's dependencies have not changed.

It should be possible to re-execute the same command if needed so this will have to be reworked.

**Comment by MattIPv4** [comment]
👀 Taking a look at this
