### ISSUE TITLE
Make activation buttons stay highlighted when clicked

### ISSUE THREAD

**Issue by abdullahmorrison** [abdullahmorrison/AlveusTwitchExtension#57]
the activations buttons are only highlighted on hover. This should also be the case when they are clicked

**Comment by MushkyQT** [comment]
Done, gonna open a PR

**Comment by MushkyQT** [comment]
@abdullahmorrison Getting permission denied, could you please provide me with access rights to this repository?

**Comment by MattIPv4** [comment]
You need to fork the repository and push to a branch there, then make a PR from your fork :) You don't need write access to this repo itself.

**Comment by MushkyQT** [comment]
Ah got it, thanks @MattIPv4
