### ISSUE TITLE
Fix Oliver's date of birth

### ISSUE THREAD

**Issue by pjeweb** [abdullahmorrison/AlveusTwitchExtension#60]
chat found out that our date(s) for oliver cannot be right, as he was featured in 2021 already in a twitter post. We did not verify this with maya, but we are pretty certain he came to alveus shortly after nugget and for sure before that tweet.

Change on the website:
https://github.com/alveusgg/alveusgg/pull/99

https://github.com/abdullahmorrison/AlveusTwitchExtension/blob/9e14f61a0839555ca50d1d3098deff4499fbad0f/src/assets/ambassadors.json#LL109C27-L109C27

**Comment by abdullahmorrison** [comment]
I'll confirm with Maya

**Comment by abdullahmorrison** [comment]
This[ instagram post](https://www.instagram.com/p/CQJyhqRDsr8/) was on june 2021, so Oliver's date of birth is definitely wrong.

**Comment by abdullahmorrison** [comment]
2021 is the DOB
