### ISSUE TITLE
Feature: Scroll ambassadors list to active ambassador

### ISSUE THREAD

**Issue by pjeweb** [abdullahmorrison/AlveusTwitchExtension#9]
It would be nice to scroll the list to the active ambassador when chosen by chat. I can send a pull request if you want.

I would probably would render some attribute (`data-ambassador-id={animal.name}`) to each button and then use something like:
```typescript
const top = animalList.current.querySelector(`[data-ambassador-id="${activeAnimal.name}"]`).offsetTop;
animalList.current.scrollTo({top, behavior: 'smooth'});
```
in the effect.

**Comment by abdullahmorrison** [comment]
great solution! I like this better than the "last seen on stream" idea. please create a PR.
